name: Bloglist pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  bloglist_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install backend packages
        run: npm install
        
      - name: Install frontend packages
        working-directory: ./frontend
        run: npm install
      
      - name: Frontend lint
        working-directory: ./frontend
        run: npm run eslint
        
      - name: Frontend e2e testing
        uses: cypress-io/github-action@v2
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          SECRET: ${{ secrets.SECRET }}
        with:
          command: npm run test:e2e
          start: npm run start:test
          wait-on: http://localhost:3003
      
      - name: Build frontend files
        run: npm run build:front
      
      - name: Heroku deploy
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        if: ${{ github.event_name == 'push' && !contains(env.COMMIT_MESSAGES, '#skip') }}
        uses: akhileshns/heroku-deploy@79ef2ae4ff9b897010907016b268fd0f88561820
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "immense-basin-88980"
          heroku_email: "gabrodzt@gmail.com"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true

  version_tag:
    runs-on: ubuntu-18.04
    needs: simple_deployment_pipeline
    steps:
      - uses: actions/checkout@v2
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        if: ${{ github.event_name == 'push' && !contains(env.COMMIT_MESSAGES, '#skip') }}
      - name: Add new tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        if: ${{ github.event_name == 'push' && !contains(env.COMMIT_MESSAGES, '#skip') }}
        uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598